return {
   { rule = { class = "Skype" },
     properties = { tag = tags[screen.count() or 1][1],
                    floating = true } },
   { rule = { class = "Viber" },
     properties = { tag = tags[screen.count() or 1][1] } },
   { rule = { class = "Firefox" },
     properties = { tag = tags[screen.count() or 1][2] } },
   { rule = { class = "Chromium" },
     properties = { tag = tags[screen.count() or 1][2] } },
   { rule = { class = "Thunderbird" },
     properties = { tag = tags[screen.count() or 1][2] } },
   { rule = { class = "Emacs" },
     properties = { tag = tags[screen.count() or 1][3] } },
   { rule = { class = "Steam" },
     properties = { tag = tags[screen.count() or 1][4] } },
   { rule = { class = "Transmission-gtk" },
     properties = { tag = tags[screen.count() or 1][6] } },
   { rule = { class = "gimp" },
     properties = { tag = tags[screen.count() or 1][6] } },
   { rule = { class = "MPlayer" },
     properties = { floating = true } },
   { rule = { class = "feh" },
     properties = { floating = true } },
}
