return
{ { rule = { class = "Skype" },
    properties = { tag = 1,
      floating = true } },
  { rule = { class = "Viber" },
    properties = { tag = 1 } },
  { rule = { class = "Firefox" },
    properties = { tag = 2 } },
  { rule = { class = "Chromium" },
    properties = { tag = 2 } },
  { rule = { class = "Thunderbird" },
    properties = { tag = 2 } },
  { rule = { class = "Emacs" },
    properties = { tag = 3 } },
  { rule = { class = "Steam" },
    properties = { tag = 4 } },
  { rule = { class = "Transmission-gtk" },
    properties = { tag = 6 } },
  { rule = { class = "gimp" },
    properties = { tag = 6 } },
  { rule = { class = "MPlayer" },
    properties = { floating = true } },
  { rule = { class = "feh" },
    properties = { floating = true } },
  { rule = { class = "Easytag" },
    properties = { tag = 4 } },
  { rule = { class = "Gnucash" },
    properties = { tag = 6 } },
  { rule = { class = "Android SDK Manager" },
    properties = { tag = 4 } },
  { rule = { class = "Quasselclient" },
    properties = { tag = 1 } },
  { rule = { class = "Hexchat" },
    properties = { tag = 1 } },
  { rule = { class = "Filezilla" },
    properties = { tag = 5 } },
  { rule = { class = "Gimp-2.8" },
    properties = { tag = 6 } },
  { rule = { class = "VirtualBox" },
    properties = { tag = 5 } },
  { rule = { class = "jetbrains-android-studi" },
    properties = { tag = 4 } },
  { rule = { class = "jetbrains-android-studio" },
    properties = { tag = 4 } },
  { rule = { class = "Monitor" },
    properties = { tag = 4 } },
  { rule = { class = "VisualVM 1.3.8" },
    properties = { tag = 4 } } }
